---
- name: add apt repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: "{{ nginx_repository }}"
    update_cache: yes
- name: install nginx
  become: yes
  become_method: sudo
  apt:
    name: nginx
    state: latest
- name: put log_format ltsv
  become: yes
  become_method: sudo
  copy:
    src: log_format_ltsv.conf
    dest: "{{ nginx_loading_conf_dir }}log_format_ltsv.conf"
  notify: reload
- name: put nginx.conf
  become: yes
  become_method: sudo
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: reload
- include: http_stub_status.yml
  when: nginx_use_http_stub_status
