---
- name: update aptitude
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install packages
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ apt_packages }}"
