---
- name: gather a fact connection port
  set_fact:
    connecting_port: "{{ ansible_env.SSH_CLIENT.split(' ')[-1] }}"
- name: git clone gitolite-admin
  sudo: yes
  sudo_user: "{{ gitolite_user_name }}"
  git:
    accept_hostkey=yes
    repo=ssh://{{ gitolite_user_name }}@localhost:{{ connecting_port }}/gitolite-admin.git
    dest={{ gitolite_user_home }}/gitolite-admin
