---
- name: create script directory
  become: yes
  become_method: sudo
  file:
    path: "{{ supervisor_scripts_dir }}"
    state: directory
- name: put listener script
  become: yes
  become_method: sudo
  template:
    src: notify-line-notify.py.j2
    dest: "{{ supervisor_scripts_dir }}notify-line-notify.py"
    mode: "u=rwx,g=rwx,o=rx"
- name: put listener config
  become: yes
  become_method: sudo
  template:
    src: listener-line-notify.conf.j2
    dest: "{{ supervisor_conf_dir }}notify-line-notify.conf"
  register: result
- name: add listener
  become: yes
  become_method: sudo
  supervisorctl:
    name: notify-line-notify
    state: restarted
  when: result.changed
