---
- name: configtest
  become: yes
  become_method: sudo
  shell: "nginx -t"
  register: result
  changed_when: "result.rc != 0"
- name: reload
  debug:
    msg: "reload after checking"
  changed_when: True
  notify:
    - configtest
    - reload after checking
- name: reload after checking
  become: yes
  become_method: sudo
  service:
    name: nginx
    state: reloaded
