---
- name: install docker.io
  become: yes
  become_method: sudo
  apt:
    name: docker.io
    state: latest
    update_cache: yes
  notify: restart

- name: install pip
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
  with_items:
    - python-dev
    - python-pip

- name: install docker-compose
  become: yes
  become_method: sudo
  pip:
    name: docker-compose
    state: latest
