---
- name: import GPG key
  become: yes
  become_method: sudo
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: add repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-trusty main'
    update_cache: yes

- name: install docker
  become: yes
  become_method: sudo
  apt:
    name: docker-engine
    state: latest
    update_cache: yes
  notify: restart

- include: docker-compose.yml
  become: yes
  become_method: sudo
